# Generated by Django 6.0.1 on 2026-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100, unique=True)),
                ('viewMode', models.CharField(default='public', max_length=10)),
                ('lastChanged', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('dueDate', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('inprogress', 'In progress'), ('awaitfeedback', 'Await feedback'), ('done', 'Done')], default='todo', max_length=20)),
                ('assignedTo', models.JSONField(default=list)),
                ('subtasks', models.JSONField(default=list)),
                ('createdAt', models.CharField(max_length=50)),
                ('updatedAt', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('ownerId', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
